// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGAaUjHAy_z5zIpK39WxsDZnmL9H6Fx5g',
    appId: '1:757164037149:web:939c01ae3c58dd054122f4',
    messagingSenderId: '757164037149',
    projectId: 'apple-store-sem-3',
    authDomain: 'apple-store-sem-3.firebaseapp.com',
    storageBucket: 'apple-store-sem-3.appspot.com',
    measurementId: 'G-DNDMSKP574',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPb5D_WdlUXcDyS6eWxsIS90Boh60qV2Q',
    appId: '1:757164037149:android:506ae8b8a12d5e784122f4',
    messagingSenderId: '757164037149',
    projectId: 'apple-store-sem-3',
    storageBucket: 'apple-store-sem-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo_doT13UQ3wpEVsBJc3R12ltBVC5QXio',
    appId: '1:757164037149:ios:ae7cb9338c65bf034122f4',
    messagingSenderId: '757164037149',
    projectId: 'apple-store-sem-3',
    storageBucket: 'apple-store-sem-3.appspot.com',
    iosClientId: '757164037149-l7cvunepfub7dvcs4t49km3nqmo5vcuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo_doT13UQ3wpEVsBJc3R12ltBVC5QXio',
    appId: '1:757164037149:ios:ae7cb9338c65bf034122f4',
    messagingSenderId: '757164037149',
    projectId: 'apple-store-sem-3',
    storageBucket: 'apple-store-sem-3.appspot.com',
    iosClientId: '757164037149-l7cvunepfub7dvcs4t49km3nqmo5vcuq.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
